spring:
  application.name: chat-service
  data:
    mongodb:
      uri: mongodb+srv://dev-root:7zEjNdGSF6N3O9yC@expat-db.ycd6koy.mongodb.net/dev?retryWrites=true&w=majority

grpc:
  server:
    port: 8072
    security:
      enabled: false

pubnub:
  host: https://ps.pndsn.com/ps.pndsn.com/