spring:
  application.name: chat-service
  data:
    mongodb:
      uri: ${MONGO_DB_URI}

grpc:
  server:
    port: 8072
    security:
      enabled: false

pubnub:
  host: https://ps.pndsn.com/ps.pndsn.com/
  pub-key: ${PUBNUB_PUB_KEY}
  sub-key: ${PUBNUB_SUB_KEY}
